### ISSUE TITLE
Lexed startup fails

### ISSUE THREAD

**Issue by fpp-gh** [lexycore/lexed#1]
Hi,
I'd like to see what Lexed does (even if it's still a WIP), but I can't get it to run.
The 'lexed' command immediately exits with this traceback :
>~/.local/bin $ lexed 
>Traceback (most recent call last):
>  File "./lexed", line 7, in <module>
>    from lexed.__main__ import main
>  File "/home/fpp/.local/lib/python3.5/site-packages/lexed/__main__.py", line 1, in <module>
    from .app import LexEd
>  File "/home/fpp/.local/lib/python3.5/site-packages/lexed/app.py", line 4, in <module>
>    from .config import Config
>  File "/home/fpp/.local/lib/python3.5/site-packages/lexed/config.py", line 191
>   line_of_text = f'{key} = {value}\n'
>                                                                    ^
>SyntaxError: invalid syntax

Is the problem somewhere in my setup ? I'm running Python 3.5, should I upgrade it ?
Thanks for any hints,
fp

**Comment by fpp-gh** [comment]
If it's not working and not supported, should it stay online ?...

**Comment by alkovpro** [comment]
If someone isn't able to see python version dependency, should that person make any complaints? :)
Sorry for such a delay though. I didn't actually decide what to do with this project. Frankly, I'm really surprised someone tried to use it. Added python version badge in REAMDE.md

**Comment by fpp-gh** [comment]
Hi, thanks for the answer (and sorry for the tongue-in-cheek comment :-)
My initial question shows I suspected the Python version right from the start : I happily admit I was unable to locate the dependency hint at the time, not being much of a github expert.
It's much better with the badge :-)

My Ubuntu machine has 3.5 and the system needs that version, so I installed 3.6 alongside then Lexed in .local.

I still had startup failures until I found that pip3 had not created the "editor" subfolder in site-packages/lexed. After I copied that from master it finally ran.

It's close to the sort of console stuff I was looking for, but as you mentioned it's still pretty raw... now I need to read the code to guess what it does (or not) and how that works :-)

**Comment by alkovpro** [comment]
Hi! Thanks for letting me know of an issue and a solution) I'll check it next week. 
What about guessing about functionality, I'm actually in pretty same position as you are)
Yes, I did update this project from the initial pyWarrior, but It was some time ago and I hadn't work with it since)
PR's and suggestions appreciated ;)
